---
title: "小泉環境相 “テレワークは治療と仕事の両立に有効”"
created_at: 2021-07-27T03:43:37+09:00
---

= 小泉環境相 “テレワークは治療と仕事の両立に有効”

[quote, 'YouTubeチャンネル「テレ東BIZ」', 'https://www.youtube.com/watch?v=7mV-zgiBjRY[小泉大臣 職務復帰会見【ノーカット】（2021年5月20日） - YouTube]']
____
今月10日に虫垂炎の緊急手術を行い、入院していた小泉環境大臣。 +
20日、本格的に公務に復帰し会見を行いました。 +
「テレワークのおかげでテレワークができた」とテレワークの重要性を強調した会見の様子をノーカットでお送りします。
____

これを書いた奴はlink:https://www.kanaloco.jp/news/government/article-508878.html[石川記者]をちょっとは見習え。

以下文字起こし。せめて「退院後」を付けろバカ野郎。

(4:18)記者「神奈川新聞の石川です。退院と復帰おめでとうございます。」小泉「ありがとうございます」記者「・・・・・・お伺いします。えっと、今コロナ禍でですね、テレワークの活用呼びかけられてます。あの図らずも大臣、あのーテレワークされたと思いますけれども、実際やってみた感想というのをお聞かせ下さい。」 +
(4:35)小泉「ほんとに今回、大変申し訳なかったのは、月曜日、緊急手術ということで、えー、法案も、委員会質疑も影響を、与えてしまいました。ただその中で考えたことは、まさすがに手術の日は無理ですけど、その後、まこういう状況の中で、国会でのリモート参加、こういったものが、整うことは、病気を抱えながら、議員活動をする立場の、議員にとっても、必要なことだなと、これは今まで、私は国会改革に取り組んできて、そういった観点から、考えたことはあまり、無かったです。しかし自分が、今回手術をして、えー病気になり、入院生活をしてる中で、まあリモートワークの整備、デジタル化の必要性というのが、こういう病の、抱えながら仕事をしてるひとと人にとっても、有効なことだと感じています。ま今後、ま私は大臣の立場で申し上げることではありませんが、そういった観点からも、議論が進んでいくことが、私としては国会にとって、大事なことじゃないかなと、そういう風に個人的には思っています。」 +
(5:58)小泉「そしてあれですね、あの、退院後、__リモートワークが出来てるおかげで、公務も、リモートで出来るものが、出来たというのは、リモートワークのおかげ__ですから、それも非常に良かったことだと思ってます。」
