---
title: "“鯖管は電気通信事業者じゃないから通信の秘密を守る義務は無い”では説明不足。でも結論は変わらない。"
created_at: 2021-01-02T22:54:22+09:00
---


= “鯖管は電気通信事業者じゃないから通信の秘密を守る義務は無い”では説明不足。でも結論は変わらない。


[abstract]
[[abstract]]
== 要約

分散型SNSサーバー管理者のための法学講座(20201202版)では、“電気通信事業者に当たらなければ「検閲の禁止」や「秘密の保護」の規定は適用されず、他に禁止する規定もない”(第2章 p.5)としているが、電気通信事業法164条3項による例外が考慮されておらず、誤りである。しかし本書が対象とする例では、通常はこの例外規定に該当することは無いと考えられる。そのため、もし最小限の修正で済ませたいのであれば、“他に禁止する規定もない”旨を、“例外はあるがまず当てはまらない”旨に書き換えることを提案する。私バカだから間違ってたらごめんね。


[[introduction]]
== はじめに

http://www.lufimia.net/lufimianetjp/sbkl/[分散型SNSサーバー管理者のための法学講座]を読んだのですが、間違ってそうな箇所を見つけてしまいました。

いろいろ書いてたら4トゥート分くらいになってしまったので、然るべき場所には要約だけ流すことにして、細かいことはここに書くことにしました。

* **“おそらく”を省略して書いています。**
* 電気通信事業法を持ち出す時は、法律名を省略しています。例えば、単に「1条」のように書いています。
* 本文中に埋め込まれているページ番号と、PDFビューアが認識するページ番号とが異なる場合、(p.1, #page=2)のようにして併記しています。
* あくまで“間違ってそうだと気付いてしまったことを放っとけない”という点での指摘です。
* 法学講座自体は楽しんで読ませていただきました。…ものすごいリソースを消費して^^;
* 数多の知識とともに、私は頭が悪いという実感を得ました。なので**多分に間違いを含んでいる可能性**があります。誰か頭のいい人後は頼んだぜよ…


[[ayamari]]
== “「電気通信事業者」じゃなければ事業法3条4条は適用されない”は誤り。164条3項による例外が考慮されていない。

[quote, 佐々木将人, 'http://www.lufimia.net/lufimianetjp/sbkl/sabakanlaw2.pdf[分散型SNSサーバー管理者のための法学講座(20201202版)(第2章 p.5)]']
____
したがって，分散型 SNS のサーバーの管理者は，電気通信事業者に当たらない以上，「検閲の禁止」や「秘密の侵害の禁止」の規定は適用されないことになるのです。他に禁止する規定もありませんから，
____

この箇所なんですが、以下の理由から誤りではないかと考えています。

. (前提)電気通信事業法2条において、電気通信事業を営むことについて“登録および届出をした者”を「電気通信事業者」と定義している。
. 164条1項において、この法律の適用外とする電気通信事業について規定している。つまり、これらに該当する者は、電気通信事業を行っていながらも、電気通信事業者ではない(ことがあり得る)。
. 同条3項において、「第一項の規定にかかわらず、第三条及び第四条の規定は同項各号に掲げる電気通信事業を営む者の取扱中に係る通信について(中略)適用する。」とある。つまり、電気通信事業者以外においても、3条および4条が適用される者が存在する。

もっとも、いわゆる“鯖管”がやってる程度の事であれば、結局3条4条は適用されないという結論そのものは変わらないかもしれません。


[[kawaranai]]
== でも結局、電気通信事業法では検閲の禁止もされないし、秘密の保護の義務もない。例外を考慮してみたが、多くの鯖管には適用されないため。

https://www.soumu.go.jp/main_content/000477428.pdf[電気通信事業参入マニュアル［追補版］(令和元年10月1日改定)]

他人に登録させ、自由に使わせる、それもダイレクト投稿(おそらく通信とみなされる)が使える、費用は事業者負担の分散SNSを常設したと仮定して、「３．電気通信事業の適用に係る判定フローチャート」(p.7-9, #page=9-11)を考えた。

「（１）『電気通信役務』に該当するか︖」::
  YES。インターネットを介せば通信することになるし、その相手(使わせてる人)は他人。

「（２）『電気通信事業』に該当するか︖」::
  YES。他人に自由に使わせてるので「他人の需要に応」じているし、ここでいう「事業」の範囲は広い(p.3, #page=5参照)ので常設すればおそらく該当する。

「（３）『事業法の適用除外』に該当するか︖」、つまり164条1項に該当するか。::
  NO。1号2号に該当しないのは比較的わかりやすいし、他人の通信を媒介しているので3号にも該当しない。(ここめちゃくちゃ解きづらい)
  footnote:[“他社の回線サービスを使って電気通信事業をやる場合、他人の通信を媒介するかDNSをやるんじゃなければ、届出しなくてもいいよ”…と理解している^^;]

「（４）『電気通信事業を営む』ことに該当するか︖」::
  NO。(2)とは違い、ここではお金を徴収しているか、直接徴収しないまでも収益を上げているかで判断される。(なので「費用は事業者負担」がポイントよ)

(この例の鯖管は)登録・届出を要しない電気通信事業。つまり電気通信事業者になる必要がない。

3条や4条は(原則として)「電気通信事業者」であることが条件なので該当しない。164条1項のいずれの号にも該当しないので、例外規定である164条3項にも該当しない。

結局(この例の鯖管は)、(あくまで電気通信事業法の上では)検閲は禁止されないし、秘密を保護する必要もない…はず^^;

(ただし、直接的であろうが間接的であろうが、運営費を得ているのであれば、登録・届出が必要と判断されるのではないでしょうか。)
footnote:[もっとも、本来この法律はアクセスラインを想定したものであるはずで(想像ですが)、杓子定規的に当てはめても、法益が無いように思います。さすがにTwitterくらいの「インフラ」ともなれば、話は別ですが。]


[[conclusion]]
== なので微修正で済みそう。

結局散々考え込んだ割には本文の微修正で済みそうだという一番おもろない結果に^^;

雑に直すなら、“例外はありますがまず当てはまらないので”とでもしておけばいい気がします。


[[law]]
== 関連法規

[[tbl]]
[quote, , 'https://elaws.e-gov.go.jp/document?lawid=359AC0000000086_20201201_430AC0000000095[電気通信事業法（昭和五十九年法律第八十六号）（平成三十年法律第九十五号による改正）]']
____

（定義）::
* 第二条　この法律において、次の各号に掲げる用語の意義は、当該各号に定めるところによる。
** 三　電気通信役務　電気通信設備を用いて他人の通信を媒介し、その他電気通信設備を他人の通信の用に供することをいう。
** 四　電気通信事業　電気通信役務を他人の需要に応ずるために提供する事業（放送法（昭和二十五年法律第百三十二号）第百十八条第一項に規定する放送局設備供給役務に係る事業を除く。）をいう。
** 五　電気通信事業者　電気通信事業を営むことについて、第九条の登録を受けた者及び第十六条第一項の規定による届出をした者をいう。

（検閲の禁止）::
* 第三条　電気通信事業者の取扱中に係る通信は、検閲してはならない。

（秘密の保護）::
* 第四条　電気通信事業者の取扱中に係る通信の秘密は、侵してはならない。
* ２　電気通信事業に従事する者は、在職中電気通信事業者の取扱中に係る通信に関して知り得た他人の秘密を守らなければならない。その職を退いた後においても、同様とする。

（適用除外等）::
* 第百六十四条　この法律の規定は、次に掲げる電気通信事業については、適用しない。
** 一　専ら一の者に電気通信役務（当該一の者が電気通信事業者であるときは、当該一の者の電気通信事業の用に供する電気通信役務を除く。）を提供する電気通信事業
** 二　その一の部分の設置の場所が他の部分の設置の場所と同一の構内（これに準ずる区域内を含む。）又は同一の建物内である電気通信設備その他総務省令で定める基準に満たない規模の電気通信設備により電気通信役務を提供する電気通信事業
** 三　電気通信設備を用いて他人の通信を媒介する電気通信役務以外の電気通信役務（ドメイン名電気通信役務を除く。）を電気通信回線設備を設置することなく提供する電気通信事業
* ３　第一項の規定にかかわらず、第三条及び第四条の規定は同項各号に掲げる電気通信事業を営む者の取扱中に係る通信について、第百五十七条の二の規定は第三号事業を営む者について、それぞれ適用する。
____

