---
title: "text/plainなメールを送る気が無いなら、いっそ消し去ってくれ。"
created_at: 2021-04-14T02:09:36+09:00
---

= text/plainなメールを送る気が無いなら、いっそ消し去ってくれ。

こんなメール来たらどう思うよってお話。**というか愚痴**。チェック体制のかけらも感じないんですけど。

....
<div class="outer-table"><table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr><td width="100%" cellpadding="0" cellspacing="0" border="0"><!-- MARKDOWN_BEGIN -->
<div class="reply-body" style="font-family: 'ＭＳ Ｐゴシック', 'ヒラギノ角ゴ W3', '源ノ角ゴシック Normal', sans-serif">
調査の結果、該当するメールマガジンについては、弊社システムの不具合により、誤って送信されたものであることが発覚しました。
ご迷惑をおかけいたしましたこと、深くお詫び申し上げます。
該当する不具合は修正いたしました。
チェック体制を整備し、再発防止を図ります。
</div><!-- MARKDOWN_END --></td></tr></table></div>
....

これ、ソース表示じゃなくて、普通に表示した状態でこういう見え方してるんですからね。(これは再現だけれど)

____
プレーンテキストメールを愛するものにとって、このようなメールは日常茶飯事であり、今さら気にするものでもありません。しかし、このように見えている人がいることは、知っておくべきではないでしょうか。少なくとも、良い印象を受けるものではないはずです。
____

こう書いたりましたよ。

本当はここまで言うつもりもなかったんだけれど、最初にした指摘が、見落としたのかなんなのか知らんけど、**スルーされちゃって**。

でも言わんと解からんでしょ。こんなメール送ってくるんだし、社内にゃ(あとSaaS業者にも)テキストメール使ってる人なんかそう居ないんでしょ。だからまあ、面倒だけど言うたりました。

というかね、そもそもの問い合わせもバグの話だし、きれいに終わらせたいのよ。バグでした直しましたすいませんでした今後きちんとチェックしますって通知が、こんなバグったメールじゃ締まらないでしょ。お願いだからいい印象を抱かせてくれよ！

…まあいろいろ書いたけど、えー……仮にE社としましょう。今回はともかく、この会社はまだきちんと返事してくる方なのよ。どうにもファウルが多くて疲れるんだけど。

特定のキーワードに反応したのか、メール全体の5%も読んでないような返信してくる会社とか(実は中身ボットだったりするのか？)、「テキストメールは配信終了しました」ってメルマガよこしてくる三木谷んとことか、そんなんに比べたらE社はまだマシなのよ。割とポンコツだけど！

というわけで、**中途半端なtext/plainを含めるくらいなら、いっそtext/htmlだけにしてくれ**というお話でした。(だってそうしたらメーラーちゃんがいいように表示してくれるし)
