---
title: "「つまり」で話を広げるな。畳め。"
created_at: 2021-06-09T02:34:40+09:00
---

= 「つまり」で話を広げるな。畳め。


[[introduction]]
== 全部書いたけど念のためにこれも書いておくねという体で、後から大事なことを書いてくる記事をたまに見る。

“コナンが好きである。金田一も好きである。つまり私はジャンプが好きである。”

…みたいな、「つまり」の後に言い換えではなく、驚きの新事実を盛り込んでくる人、たまにいるよね。つまり私はこの用例にもやもやしている。 #自己矛盾

…というトゥートを末代に投げようと思ったけど、ネタなのか主張なのか分かりにくいので、いろいろ書いてたら、思いのほか長くなってしまった。タイムラインの海に流してもいいんだけど、ちょっともったいないので、ブログの肥やしにしようかなと。


[[hayoie]]
== 書いた人しか知らないことは「つまり」よりも前に書いて欲しいんだけど。

[quote, , 'https://kotobank.jp/word/%E8%A9%B0%E3%82%8A-572464[詰りとは - コトバンク]']
____
デジタル大辞泉「詰り」の解説

「地図の上方、詰まり北方は山岳地帯である」
____

これは地図の上は北だってことが常識だから成り立つ。

地図の上が北だってことが常識じゃなかったら、ここで「つまり」を使われたところで、“なにそれしらない先におしえてよ…”ってなってしまう。


[[matomero]]
== 「つまり」は疑問を解消させる言葉であって、疑問を増やす言葉ではない気がするのだけど。

「つまり」って、今まで言ったことを短い言葉でまとめたり、違う言葉で言い直したりする時に使う言葉じゃないんかね。なので、今まで読んでごちゃごちゃしていた頭が、ここでスッとまとまるからこそ、生きてくる言葉だと思う。

それなのに、「つまり」以降に初めて出てくることが書いてあるから、逆に頭が散らかってしまう。書いた人は“そんなことは前提知識でしょ？”と思って書いてるのかもしれないけれど、読む人がそれを知っているとは限らないし、そもそも書いた人しか知らないことを「つまり」以降に書いてたりもする。

まとめるつもり、終わらせるつもりで書かれた言葉が、次週へ続くになっちゃってるんだから、そりゃもやもやしますよ。


[[ketsu]]
== 言いたいことはきれいに書ききろう。

まあ、物語なら疑問を残すのも楽しいけど、主張だったらきれいに書き切りたいじゃない。つまり、そんなお話でした。
